# Generated by Django 4.1.9 on 2023-05-11 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Buyer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Buyer name")),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Product name")),
                ("price", models.FloatField(verbose_name="Product price")),
            ],
        ),
        migrations.CreateModel(
            name="Seller",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Seller name")),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.IntegerField(verbose_name="Quantity")),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("shipping", "Shipping")],
                        default="pending",
                        max_length=10,
                        verbose_name="Order status",
                    ),
                ),
                (
                    "shipping_code",
                    models.CharField(blank=True, default=None, max_length=25, verbose_name="Shipping code"),
                ),
                ("buyer", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="order.buyer")),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="order.seller")),
            ],
        ),
    ]
