# Generated by Django 4.1.9 on 2023-05-11 03:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="shipping_code",
            field=models.CharField(blank=True, default=None, max_length=25, null=True, verbose_name="Shipping code"),
        ),
    ]
